"""HTML newsletter generation."""

import html
from datetime import datetime
from typing import Iterable

from youtube_digest.models import Article
from youtube_digest.ebook.epub_builder import build_source_notes


def create_newsletter_html(articles: Iterable[Article]) -> str:
    import markdown

    today = datetime.now().strftime("%B %d, %Y")
    html_parts = [
        """
        <!DOCTYPE html>
        <html>
        <head>
            <meta charset="utf-8" />
            <style>
                body { font-family: Georgia, serif; font-size: 18px; max-width: 700px; margin: 0 auto; padding: 20px; background: #f9f9f9; color: #333; }
                .header { text-align: center; padding: 30px 0; border-bottom: 3px solid #333; margin-bottom: 30px; }
                .header h1 { margin: 0; font-size: 32px; letter-spacing: 2px; }
                .header p { color: #666; font-size: 18px; margin: 10px 0 0 0; }
                .article { background: white; padding: 30px; margin-bottom: 30px; border-radius: 5px; box-shadow: 0 2px 5px rgba(0,0,0,0.1); }
                .article-intro { background: #f8f8f8; padding: 15px 20px; border-left: 4px solid #666; margin-bottom: 25px; font-size: 16px; color: #555; line-height: 1.6; }
                .article-content { font-size: 18px; line-height: 1.9; }
                .watch-link { display: inline-block; margin-top: 20px; padding: 12px 24px; background: #c00; color: white; text-decoration: none; border-radius: 5px; font-size: 16px; }
                .source-notes { margin-top: 2em; padding-top: 1em; border-top: 1px solid #ddd; font-size: 0.9em; color: #555; }
                .source-notes dt { font-weight: bold; margin-top: 0.6em; }
                .source-notes dd { margin-left: 0; }
                .footer { text-align: center; color: #999; font-size: 14px; padding: 20px; }
            </style>
        </head>
        <body>
        """
    ]
    html_parts.append(f'<div class="header"><h1>YOUR YOUTUBE DIGEST</h1><p>{html.escape(today)}</p></div>')

    for article in articles:
        article_html = markdown.markdown(article.markdown, extensions=["extra"])
        html_parts.append(
            f"""
            <div class="article">
                <div class="article-intro">
                    <em>Based on "{html.escape(article.title)}" from <strong>{html.escape(article.channel)}</strong>.</em>
                </div>
                <div class="article-content">{article_html}</div>
                {build_source_notes(article)}
            </div>
            """
        )

    html_parts.append('<div class="footer">Generated by YouTube Digest</div></body></html>')
    return "\n".join(html_parts)
